[theme]

# Primary accent for interactive elements
primaryColor = '#1A1A1A'

# Background color for the main content area
backgroundColor = '#242442'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#1A1A1A'

# Color used for almost all text
textColor = '#FFFFFF'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"
